fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
      - id: check-yaml
        fail_fast: true # applies to check-yaml as well as every hook below
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: no-commit-to-branch
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff-check
        exclude: "(?x)^(tests/|src/cylutils/resources/)"
        args: [--fix]
      - id: ruff-format
        exclude: "(?x)^(tests/|src/cylutils/resources/)"

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
        files: requirements.txt

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [--severity-level=high, --confidence-level=high]
