name: release workflow

on:
  release:
    types: [published]
    branches: [main]

concurrency:
  group: ci-tests-${{github.ref}}-release

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build distribution job
    steps:
      - name: checkout the repo
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # full history needed for setuptools-scm

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: validate release tag
        run: python .ci-tools/release_publisher.py ${{github.ref_name}}

      - name: build
        run: python -m build

      - name: upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  test_pypi_deploy_job:
    runs-on: ubuntu-latest
    name: deploy to test pypi job
    needs: build_job
    environment:
      name: test.pypi.org
      url: https://test.pypi.org/project/cylutils/
    steps:
      - name: download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: deploy to test.pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{secrets.TEST_PYPI_KEY}}

  prod_pypi_deploy_job:
    runs-on: ubuntu-latest
    name: deploy to production pypi job
    needs: test_pypi_deploy_job
    environment:
      name: pypi.org
      url: https://pypi.org/project/cylutils/
    steps:
      - name: download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: deploy to pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{secrets.PYPI_KEY}}
